version: '3.1'

services:  

  mongo:
    image: mongo
    container_name: ads-user-mongo
    restart: always
    ports:  # for demo/debug purpose only
     - "27018:27017"

  ads-api:
    image: ads-api:v1
    command: node ./dist/app.js
    restart: always
    container_name: ads-api
    working_dir: /opt/ads-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  security-api:
    image: security-api:v1
    command: bash -c "cd dist && ls -a &&  npx migrate-mongo up &&  node ./app.js"
    restart: always
    container_name: security-api
    working_dir: /opt/security-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo