POST http://localhost:3001/api/register
Content-Type:application/json

{
  "name": "joao2",
  "email": "j2356123412344oao@te2fst.com"
}
###
POST http://localhost:3001/api/login
Content-Type:application/json

{
  "name": "joao2",
  "email": "j2356123412344oao@te2fst.com"
}
###
POST http://localhost:3001/api/login
Content-Type:application/json

{
  "name": "admin",
  "email": "admin@admin.com"
}

###
PATCH http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwpbDo0FcdTAwMWF9VCUswot_wppcdTAwMGXDtlx1MDAxMMKOXHUwMDFlw4DDrmfDt8OSQ8OFw6DDoVx1MDAwYlbDm8OvwqF2PCdDwo7Duz7CvHMjwrxcdTAwMDbDsGnDicOFc1x1MDAwNERsXHUwMDE4XHUwMDFmwotcdTAwMDIhw75cdTAwMTPDnsKsaMOGOsObXHUwMDEywpBcdTAwMTc-wqJcdTAwMTHCmjhjw7vChsOBQMKKJcOwXHUwMDEyLcOTw6lcdTAwMTRcYi7CpSnDr8OLQFx1MDAwZVx1MDAwNsKCJCgkZsKEdcK8XHUwMDAwwpjCpmTChFx1MDAxMGZfXHUwMDE1woQ5w6VLw705wqzCpcO_w7zCmMKmw69uw7bCmUvCt8KhfsKQwpFiw7_DvFx1MDAxYcOqwqnCrSlDwrJ_w6XCslPCv1x1MDAwMDbDrFwiTMKlclnCkWbDhcK4w5TCvmNjwpE2XHUwMDAzOlx1MDAwMMO1w5TCpsKsOsO7e1x1MDAwMW05XCJhKMKtwpNgbC7CjDHCuHLCiTFcXFx1MDAxYTnCucKVwrtyXHQ5bi3Dg1x1MDAwM8Oew5ttO8ONXHUwMDEwwpNFwpjDu8OawpLDrMO-XHUwMDEyUsOLwqvDnEVnfMKow6w6wqjCrMKLw6tcdTAwMDHDtcKAXHUwMDA0VsOWw4LCrMOdRsKWwoYnw4XCjcOSOsOUK3Ujw6YiLCJpYXQiOjE2MTg0MzczNDEsImV4cCI6MTYxODQ0MDM0MX0.GkdJVb2ZQQQq-IsGaidl89VNTclx2RdesHLXEqlIOVE

{
   "email": "hghh@fgagalga.com"
}

###
DELETE http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiPsOiXyFqwpjCinNQw6TChEHCr8KabFx1MDAwMMKGXHUwMDAywrNpUiB_XHUwMDAzM8OSwqEkXHUwMDE2w4fCo8OCfcK6w4RLXHUwMDFmw4HDs0UlXHUwMDBmfcKpwqg7YMOUwqZcdMOpaHBGXCJ7wqBcdTAwMTE4MkQ9RVx1MDAxZT_CtUHDpcK4w7PCsnbDmVPCsMKcZsKlwq7DvsOWWMK8XFzCgcOLwrptPcOpw4dRwpdOw6VWwoRqw6BcdTAwMTUhw7bDq1AwwrtwwqzCicONXHUwMDE4NnHDtsOgXGZcdTAwMDJIXCIow6zCssKEOFxuw6PCi8Kew7xcdTAwMDcrw712TcKXw6_Ci8OaXHUwMDE3wqvDuW9cdTAwMWXCisOMI1x1MDAwYsOyXVx1MDAwN8KZV3dcdTAwMGbDk8KtK1x1MDAwMcKkamRoYMOCXHUwMDFmXFw2XHUwMDE0J8KOw6JcdTAwMDTDqTzDrFx1MDAxOWrCr23CgsKRKMOjMsOKOMKhaMOBwqd9XHUwMDAzwqBVwpzCnz7CtiHCqU_DjFx1MDAxMF0kwr7Dv0_DnFx1MDAxM8OAXHUwMDBlcVx1MDAxZUVMwrPCvsOgwpnDqiFcdTAwMDArw5jDuHLCsUbDl8KYw5DCl8KyMj1XX8OLfsOZRW5kS8KbXHUwMDE1fUgpw5Ynw4vCqlxuw48iLCJpYXQiOjE2MTg0MzczMTEsImV4cCI6MTYxODQ0MDMxMX0.dnNg9NhEJUodIVlnlg5VKKGGDJY5qFlKG6rBBCVt0t4
###
POST http://localhost:3001/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiK8O5w7DDu0BcdTAwMTNGwrrCgMOzXHUwMDA1XG7DtMOQw7JcdTAwMWFcXMK0wozDhyfDqFx1MDAwNsK2w519dVjDosKyNsOFwoTDk8KLXHRcdTAwMDZUbsKmTk7DpMKxLVx1MDAxY1x1MDAwZcKBw6tGwpzDvcK4XHUwMDBiQGDCoMKCXHUwMDE3XHUwMDE4w7HCkC5Aw5XCtFx1MDAxYcKww5TCqCvCiCTCtsKIcHQjY8KyQlx1MDAwM8OYW8OTwqQyQcK-XHUwMDE1VkJewpdfw4YvWMOAWcOtwrXDocO6W8OVaVrCq8K2bVx1MDAxMMKoIcK7XHUwMDEzw5lCw7rDrls1w6zChsOAXXE2w7XCicKhQ8KKO8ONwpFNwp3DhsO3w4dkUjQqYcKZcMO2wq3CrMKTw5c2Y1x1MDAxZFx1MDAxMMKCalFaw4ZcdTAwMTDDjVx1MDAwZXbDj8K4LizDulx1MDAwN8Opw5_DmifCs0DDhMKpw7HCm8K2bsKyM8KgScKBVlVbMlx1MDAxMifCiMOtIMOsw7PDmVVcdTAwMTBcdTAwMTJBwoXCj8KgRT3DnsOvw4zCllxcw6hcZsOkXHUwMDBmw6Ezwq4_w5Z-XHUwMDA3wrJ7Ui1VSsOLwr_DmUggwq05ZMOVwoBrwrrCusK0wpUgw6_DqMOowpHDvGZcdTAwMWPCmSIsImlhdCI6MTYxODQzODMyMSwiZXhwIjoxNjE4NDQxMzIxfQ.ZK00XhWohCp2P2_XZb-hZ2xutSw8U8Yop9aSHaWlNow
Content-Type: application/json

{
  "productId": "ae03c404-a665-4ace-a4f4-39e59f17fff7"
}
###
DELETE http://localhost:3001/api/users/favorites/ae03c404-a665-4ace-a4f4-39e59f17fff7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiK8O5w7DDu0BcdTAwMTNGwrrCgMOzXHUwMDA1XG7DtMOQw7JcdTAwMWFcXMK0wozDhyfDqFx1MDAwNsK2w519dVjDosKyNsOFwoTDk8KLXHRcdTAwMDZUbsKmTk7DpMKxLVx1MDAxY1x1MDAwZcKBw6tGwpzDvcK4XHUwMDBiQGDCoMKCXHUwMDE3XHUwMDE4w7HCkC5Aw5XCtFx1MDAxYcKww5TCqCvCiCTCtsKIcHQjY8KyQlx1MDAwM8OYW8OTwqQyQcK-XHUwMDE1VkJewpdfw4YvWMOAWcOtwrXDocO6W8OVaVrCq8K2bVx1MDAxMMKoIcK7XHUwMDEzw5lCw7rDrls1w6zChsOAXXE2w7XCicKhQ8KKO8ONwpFNwp3DhsO3w4dkUjQqYcKZcMO2wq3CrMKTw5c2Y1x1MDAxZFx1MDAxMMKCalFaw4ZcdTAwMTDDjVx1MDAwZXbDj8K4LizDulx1MDAwN8Opw5_DmifCs0DDhMKpw7HCm8K2bsKyM8KgScKBVlVbMlx1MDAxMifCiMOtIMOsw7PDmVVcdTAwMTBcdTAwMTJBwoXCj8KgRT3DnsOvw4zCllxcw6hcZsOkXHUwMDBmw6Ezwq4_w5Z-XHUwMDA3wrJ7Ui1VSsOLwr_DmUggwq05ZMOVwoBrwrrCusK0wpUgw6_DqMOowpHDvGZcdTAwMWPCmSIsImlhdCI6MTYxODQzODMyMSwiZXhwIjoxNjE4NDQxMzIxfQ.ZK00XhWohCp2P2_XZb-hZ2xutSw8U8Yop9aSHaWlNow
Content-Type: application/json
###
GET http://localhost:3001/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiK8O5w7DDu0BcdTAwMTNGwrrCgMOzXHUwMDA1XG7DtMOQw7JcdTAwMWFcXMK0wozDhyfDqFx1MDAwNsK2w519dVjDosKyNsOFwoTDk8KLXHRcdTAwMDZUbsKmTk7DpMKxLVx1MDAxY1x1MDAwZcKBw6tGwpzDvcK4XHUwMDBiQGDCoMKCXHUwMDE3XHUwMDE4w7HCkC5Aw5XCtFx1MDAxYcKww5TCqCvCiCTCtsKIcHQjY8KyQlx1MDAwM8OYW8OTwqQyQcK-XHUwMDE1VkJewpdfw4YvWMOAWcOtwrXDocO6W8OVaVrCq8K2bVx1MDAxMMKoIcK7XHUwMDEzw5lCw7rDrls1w6zChsOAXXE2w7XCicKhQ8KKO8ONwpFNwp3DhsO3w4dkUjQqYcKZcMO2wq3CrMKTw5c2Y1x1MDAxZFx1MDAxMMKCalFaw4ZcdTAwMTDDjVx1MDAwZXbDj8K4LizDulx1MDAwN8Opw5_DmifCs0DDhMKpw7HCm8K2bsKyM8KgScKBVlVbMlx1MDAxMifCiMOtIMOsw7PDmVVcdTAwMTBcdTAwMTJBwoXCj8KgRT3DnsOvw4zCllxcw6hcZsOkXHUwMDBmw6Ezwq4_w5Z-XHUwMDA3wrJ7Ui1VSsOLwr_DmUggwq05ZMOVwoBrwrrCusK0wpUgw6_DqMOowpHDvGZcdTAwMWPCmSIsImlhdCI6MTYxODQzODMyMSwiZXhwIjoxNjE4NDQxMzIxfQ.ZK00XhWohCp2P2_XZb-hZ2xutSw8U8Yop9aSHaWlNow
Content-Type: application/json

###
DELETE http://localhost:3001/api/user/5c4875fb-ce9b-49fb-99b8-d4bbf49d0f44
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDAzw47DqMOnwrDDvFXDlUbCvy_CnV3DqmbCr2Zxwokpwr9cdTAwMDIhwpjDlcOfw7ouScOYb8Odw4olesOdwojComJSXHUwMDE2wq1ow7HDqcKfa23ChMO0bFx1MDAxMWhANVx1MDAwMTVVbV3DkVx1MDAxM8Oew6RgMVx1MDAwNVx1MDAwNVx1MDAxMcKSw443w7XCucK6wrzDkcKfaFx1MDAxNMKwwrRbXHUwMDExw4nDjsK1wqjDqD5cdTAwMDPCnlx1MDAxZMOaw5Buwq_CgcKIwp9Tw4vCksKgMDDDl8KqXHUwMDA2worDpsOxwrjDlMK1Y8KNw6TDscOKXG5cdTAwMWPDh1x0TcKLZ8Kww4rCu0xGd3VcdTAwMDRcdTAwMTfDjWfCt8K_wofCqGZdWcOhV1bDoFxmw7bDslvClMKswonDrV1Tw6rCgcO6fzHDncOPXFwtdCfDgVkuw5VewrPCrTnDvkjDhMO3w5pud8Ouw4vDgMKdXHUwMDAzJnw7wqLCucOpwq_Cn8OdLcOXSMK0w5fCsSxkXHUwMDAxXHUwMDE5wrXCuzzCkSFcZlBcdTAwMDLCl8OdXHUwMDAxw51TworChHdcdTAwMGY8XHUwMDE1XGJcdTAwMTBcdTAwMGLDj8KXKVx1MDAxYlx1MDAxM8Ogw4k1w6nCrHfCgcKKwoJcXGhBwpskwqpcbmFcdTAwMWPCuMO0IiwiaWF0IjoxNjE4NDM4NDAzLCJleHAiOjE2MTg0NDE0MDN9.T-R7Q1mNzzn-1PEgYgUT39XdD8BTone4rmhT5ndgh4E
###
GET http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDAzw47DqMOnwrDDvFXDlUbCvy_CnV3DqmbCr2Zxwokpwr9cdTAwMDIhwpjDlcOfw7ouScOYb8Odw4olesOdwojComJSXHUwMDE2wq1ow7HDqcKfa23ChMO0bFx1MDAxMWhANVx1MDAwMTVVbV3DkVx1MDAxM8Oew6RgMVx1MDAwNVx1MDAwNVx1MDAxMcKSw443w7XCucK6wrzDkcKfaFx1MDAxNMKwwrRbXHUwMDExw4nDjsK1wqjDqD5cdTAwMDPCnlx1MDAxZMOaw5Buwq_CgcKIwp9Tw4vCksKgMDDDl8KqXHUwMDA2worDpsOxwrjDlMK1Y8KNw6TDscOKXG5cdTAwMWPDh1x0TcKLZ8Kww4rCu0xGd3VcdTAwMDRcdTAwMTfDjWfCt8K_wofCqGZdWcOhV1bDoFxmw7bDslvClMKswonDrV1Tw6rCgcO6fzHDncOPXFwtdCfDgVkuw5VewrPCrTnDvkjDhMO3w5pud8Ouw4vDgMKdXHUwMDAzJnw7wqLCucOpwq_Cn8OdLcOXSMK0w5fCsSxkXHUwMDAxXHUwMDE5wrXCuzzCkSFcZlBcdTAwMDLCl8OdXHUwMDAxw51TworChHdcdTAwMGY8XHUwMDE1XGJcdTAwMTBcdTAwMGLDj8KXKVx1MDAxYlx1MDAxM8Ogw4k1w6nCrHfCgcKKwoJcXGhBwpskwqpcbmFcdTAwMWPCuMO0IiwiaWF0IjoxNjE4NDM4NDAzLCJleHAiOjE2MTg0NDE0MDN9.T-R7Q1mNzzn-1PEgYgUT39XdD8BTone4rmhT5ndgh4E

###
PATCH http://localhost:3001/api/user/8257c837-9165-46ba-b9eb-93a02ff3574a
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDAzw47DqMOnwrDDvFXDlUbCvy_CnV3DqmbCr2Zxwokpwr9cdTAwMDIhwpjDlcOfw7ouScOYb8Odw4olesOdwojComJSXHUwMDE2wq1ow7HDqcKfa23ChMO0bFx1MDAxMWhANVx1MDAwMTVVbV3DkVx1MDAxM8Oew6RgMVx1MDAwNVx1MDAwNVx1MDAxMcKSw443w7XCucK6wrzDkcKfaFx1MDAxNMKwwrRbXHUwMDExw4nDjsK1wqjDqD5cdTAwMDPCnlx1MDAxZMOaw5Buwq_CgcKIwp9Tw4vCksKgMDDDl8KqXHUwMDA2worDpsOxwrjDlMK1Y8KNw6TDscOKXG5cdTAwMWPDh1x0TcKLZ8Kww4rCu0xGd3VcdTAwMDRcdTAwMTfDjWfCt8K_wofCqGZdWcOhV1bDoFxmw7bDslvClMKswonDrV1Tw6rCgcO6fzHDncOPXFwtdCfDgVkuw5VewrPCrTnDvkjDhMO3w5pud8Ouw4vDgMKdXHUwMDAzJnw7wqLCucOpwq_Cn8OdLcOXSMK0w5fCsSxkXHUwMDAxXHUwMDE5wrXCuzzCkSFcZlBcdTAwMDLCl8OdXHUwMDAxw51TworChHdcdTAwMGY8XHUwMDE1XGJcdTAwMTBcdTAwMGLDj8KXKVx1MDAxYlx1MDAxM8Ogw4k1w6nCrHfCgcKKwoJcXGhBwpskwqpcbmFcdTAwMWPCuMO0IiwiaWF0IjoxNjE4NDM4NDAzLCJleHAiOjE2MTg0NDE0MDN9.T-R7Q1mNzzn-1PEgYgUT39XdD8BTone4rmhT5ndgh4E

{
  "email": "newwfffffffffffffffffwwwww@fgagalga.com"
}