POST http://localhost:3003/api/register
Content-Type:application/json

{
  "name": "joao2",
  "email": "joao@te2fst.com"
}
###
POST http://localhost:3003/api/login
Content-Type:application/json

{
  "name": "joao2",
  "email": "joao@te2fst.com"
}
###
POST http://localhost:3003/api/login
Content-Type:application/json

{
  "name": "admin",
  "email": "admin@admin.com"
}

###
PATCH http://localhost:3003/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwptOwofDmkcrw4RLacKIMVx1MDAwMMK6wrJcdTAwMGbDvSkreMKPVjvCr2_DuMOCXsO5N8KDI8O2wp5cdTAwMDIkcsOwecKIXHUwMDEyXHUwMDAweMOxw6vDnVx1MDAwZTTCo8KEScKZN1x1MDAwZsO4w65JUcOrOSRcdTAwMWNZwq5cdTAwMDNcdTAwMGZwwofDiMK8w7ttMcK3wrTCvsKYwptvI8KwVlx1MDAxNlLCqcO6w4fDucKfw63DtmhWwqomXHUwMDAyXHUwMDE2wqPCocOjwqHDlFLDrsOZwq9vXHUwMDFjwoXDjcOBYVx1MDAwM1Ynw4JcdFx1MDAxY8K4wrohXHUwMDE2w7TCmcK7w7pXWcO6ecK4wqLCkMKtXHUwMDBmXHUwMDAywqnDvsK9blfCj8OITcOnw4nCvsKvw6XCkFx0w7Z4M8KGwpjCuMKPwrHCm8OKMsK5w7txw5HDvVx1MDAwNMKBUcKMwr9Ow7VcZk0uwo7CtlTDlzZcdTAwMWFcdTAwMDR8fsO8L2DDj25sw4LCoMK7QlDDhVxyw4PDv8KTwpHDh8KZwpfDjVx1MDAxNF1cdTAwMDPDiVx1MDAxNcKzw5PCksOCfFxcw5TCvcO4wpw0NsKVwro_wqs-JsOLTFnCp3jCsy0kwoA1PcOFVlFkw4TDpX58P8K0J8OiwrBDw7QwIiwiaWF0IjoxNjE4MzYxNDg4LCJleHAiOjE2MTgzNjE3ODh9.Hi-2lRxDBxuM_-LB41yHMvG4ErjOi1X6rXW6_rwGtB0

{
   "email": "hghh@fgagalga.com"
}

###
DELETE http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoifcKywo7DrcKSwrPClMOheGNwwqjDhsKow6Ncbi7DpXU1wpvCqHNMw5Rdw5zClsKLRy7Dk3NcdTAwMDLDoVx1MDAxYcKbwoFiwplOw4ZcdTAwMTTCjMKuwqPDgXvCrsKmbFPCu1x1MDAxNVx1MDAwZcOBwoBhw5XDm8KEeFx1MDAxNcKdRCjDvcKewr3DkVx1MDAwMsOvw57DrCY6XsKjfVx1MDAxZFx1MDAxN8KpwrpVw5rCiDTDjcKrXHUwMDFicsKHNlx1MDAxOVx1MDAxYybDqzJuw6XCn8OQOWFkWFxmeDQ3TypawqZUw5fColx1MDAwNjVdXGLCmXfCg1x1MDAxZcK0w43DsFx1MDAxY8OAIcO5XHUwMDFmTcOCXGbCqsOzw63CmcKkwo7Cp1x1MDAwMsOaw5jDg8KNwr4rw6LCkkV-wrh0wrRDw5DCuVx1MDAxNVx1MDAxZMOtwqHCh2PCk8KoXGZubU_Dj8Kcw6XDnG14wq9kw6J5w7nChlDDqMOlw6HCg8OWw73DqFx1MDAwNzh-wqXCvMKQYj_Co07CjcKZTsKfwplcdTAwMWZrTFx1MDAxZMORYnDCkCnDocOYS23DucOAwpPCtcO4RcOWUcK6N1x1MDAwYlx1MDAwMFDDmGvDvynDryMkw45aXHTCplfDm1xcw7HDtWvCisOiw77DlMO6SSIsImlhdCI6MTYxODE3NTQ1OSwiZXhwIjoxNjE4MTc1NzU5fQ.lFbAnvb5E38upLsn98k7YnMKaAYbjXx0dklLyPvIwGs
###
POST http://localhost:3003/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidWnDtsKaw7ZqXGY8wo9EYsOXw5DDkVrDo8K-wpJxw7JcdTAwMDPDhlx1MDAwN1x1MDAxMnx3w4nDjSp1WsOIwq88wpfClFx1MDAwZlx0PcKvcsK5XHUwMDE5w6bCnD0gw6DCvXXDuEvDk8KdwqDDilggw77DgVx1MDAxYlx1MDAxM1Znw4TCgVx1MDAxNsOmw5ViXHUwMDA2a1x1MDAxNsKnI8Kjwo3DoHs1wpDCnMKXJiPDosKtw45eaFxiwpxcdTAwMGLDjVx1MDAwN1_CvMO0LVpcdTAwMGXCiVDCncKoTcKcXHUwMDA1w47CqVTDjXrCrsOEa1x1MDAxN8OJwqXCtlVcdTAwMTfCmFx1MDAxZlx0XHUwMDAxw69cXGLCold7WMKzwqBcdEPCqUwtNUtMwofDssODL0fClj3CrsOjwqHCnnpOw4Fpw4NHwo3DqsOCwrLCpMKSwqonXHUwMDFlTsKjw4VcXGB0wqHCjFx1MDAxYcK1woB0dcO0w6FKwojCpGdnwpvCqXZcdTAwMGXCrFx1MDAwNlx1MDAxYsOXVFXCkMKqXHUwMDA3wr5-w6I8w4A-XVx1MDAxNMK1wqBpLDJNb1x1MDAxMcKJNMKceSXDki3Cg8OGworCqMK0w4FQw6TCqsK9w5DCocO4w497e8KvW8OAw6tFwq90Q8OrScK2XCJcdTAwMTB3wokiLCJpYXQiOjE2MTgyNzE3ODAsImV4cCI6MTYxODI3MjA4MH0.RkQ_4lOv6W-Zhb1Si41mBSl9Q10QJbkE-4Gj5cy9db4
Content-Type: application/json

{
  "product_id": "1f55d48c-4bda-4d39-81a1-5c2476f192b4"
}
###
DELETE http://localhost:3003/api/users/favorites/1f55d48c-4bda-4d39-81a1-5c2476f192b4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoifcKywo7DrcKSwrPClMOheGNwwqjDhsKow6Ncbi7DpXU1wpvCqHNMw5Rdw5zClsKLRy7Dk3NcdTAwMDLDoVx1MDAxYcKbwoFiwplOw4ZcdTAwMTTCjMKuwqPDgXvCrsKmbFPCu1x1MDAxNVx1MDAwZcOBwoBhw5XDm8KEeFx1MDAxNcKdRCjDvcKewr3DkVx1MDAwMsOvw57DrCY6XsKjfVx1MDAxZFx1MDAxN8KpwrpVw5rCiDTDjcKrXHUwMDFicsKHNlx1MDAxOVx1MDAxYybDqzJuw6XCn8OQOWFkWFxmeDQ3TypawqZUw5fColx1MDAwNjVdXGLCmXfCg1x1MDAxZcK0w43DsFx1MDAxY8OAIcO5XHUwMDFmTcOCXGbCqsOzw63CmcKkwo7Cp1x1MDAwMsOaw5jDg8KNwr4rw6LCkkV-wrh0wrRDw5DCuVx1MDAxNVx1MDAxZMOtwqHCh2PCk8KoXGZubU_Dj8Kcw6XDnG14wq9kw6J5w7nChlDDqMOlw6HCg8OWw73DqFx1MDAwNzh-wqXCvMKQYj_Co07CjcKZTsKfwplcdTAwMWZrTFx1MDAxZMORYnDCkCnDocOYS23DucOAwpPCtcO4RcOWUcK6N1x1MDAwYlx1MDAwMFDDmGvDvynDryMkw45aXHTCplfDm1xcw7HDtWvCisOiw77DlMO6SSIsImlhdCI6MTYxODE3NTQ1OSwiZXhwIjoxNjE4MTc1NzU5fQ.lFbAnvb5E38upLsn98k7YnMKaAYbjXx0dklLyPvIwGs
Content-Type: application/json
###
GET http://localhost:3003/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDAwPcOKXHUwMDE2a1x1MDAwMWjCsMKMJXLDrlx1MDAxM1x1MDAxNsOVRsKlw5I1cDXDiyrCvVx1MDAxYsKGXHUwMDBiwo1pw4hnwr_DqX3Cv8O3ZlPDl1xcR1x1MDAwZW_Cim5cdTAwMTLDscObw6TCnSZkw7jDpMOqw4lcYlx1MDAxYcOCXHUwMDEyXHUwMDA3wrfDqMK9wq3DjVx1MDAxMsK4JTDCqX9cdTAwMWbDh2jCvWXDq8Ofw4jCrMOFQMKFw4bDgETDhCcmw4dmw5DDn8KOw7Fyw4TDksKsZHJcdTAwMTI0YDxcdTAwMDDCj8Oow57Ds2xMXHJPw4zDilI0YjZsb1x1MDAwNsK0aXVcdTAwMTbChyzDh8OtRV9Kw4PClyzDmjpMw6PDqcKrw7RcdTAwMWNcdTAwMGYkMsOhfMOvXHUwMDA2OzpgwqpcdMO1Llx1MDAxMVx1MDAxMcKSw4d4wot4bS1dWz_CkXrCjFx1MDAxMsOXJcO7wrXDp8K6w5xQw69cdTAwMTDDo8OkXVx1MDAxNT_ChMO4bT1cYsKYw41OwrjChsOCeMKvwrvClMK1XHUwMDA0wrjDqDnColbCpThcdTAwMTHClcOLXHUwMDA0XHUwMDFiwrBZOFksXHUwMDFhw5Rjw67DhHPCl3jCocOBwq0vSsKUfUzCosOyXHUwMDFjwpfDono7XHUwMDA0wpvCjmVcdTAwMTnDi00lIiwiaWF0IjoxNjE4MjcxMjU0LCJleHAiOjE2MTgyNzE1NTR9.0JsixAe70Swe8JRNa5ZWxuL8WQCpVcG39zt8mLzP2ik
Content-Type: application/json

###
DELETE http://localhost:3003/api/user/baccb8b8-ccf5-44fd-b347-e0566421a10c
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwoFcdTAwMDEjXHUwMDAxPsOzwo5yXCIrwp5ybMOGw55mL1InwpZyXHUwMDA0wprCrFx1MDAxZMO1w59xw69cdTAwMDMow71cdTAwMTN3XHUwMDFkw5HDk8O3JSpCIcONd8KMw4dawpvDpjp1wqbDvsKkVXbCuEZRXsODw67Dj8Oxf350XHUwMDA2XHUwMDA2wp7DjnjDrSTDtlvCo8K9V8OewpM2f8O5XHUwMDA3w4UgQ8Olw73Cq2HDsWpvwr_Co1x1MDAwMFx1MDAwM3csK8K4c0bDvcOmw4lhwo5cdTAwMDbDlzUlQMOvLMKkwpdObcKfI05ewofChlx1MDAwNcK_ZMOtw61ISMOBwqxhwo09NcOHb8KsR8KnSMKoMnPDu8Otw6pWU8O-XHUwMDA2JcO2RsOSRsOswqJib8KyXHUwMDA1RsOSw7xcdTAwMDHCt8KiwrtiwoUww7JIw4TDrsO0wrfCqV5cdTAwMWFcdTAwMWVwXG7Cq8O8w5nCp1x1MDAwN8Khw6XDgMOQwqVcdTAwMTdGw43DjMKvIFx1MDAxOcKANMKQw5ZxYXbCosOtbnVeWlx1MDAwZcKCJsKIXcKEXHUwMDE2eGTDusO1w63CtFx1MDAxZic9wqrCu2JowopcdTAwMTlcdTAwMTMgw7pHXHUwMDE1w6BcdTAwMTjCrkbDt1x1MDAxM8KNJcKeMCIsImlhdCI6MTYxODI3MjUwNywiZXhwIjoxNjE4MjcyODA3fQ.AKzmLdEMA-n1cDj_60XkCuIQtA8jU8CUzhSvJeSdQN0
