POST http://localhost:3003/api/register
Content-Type:application/json

{
  "name": "joao2",
  "email": "j2356123412344oao@te2fst.com"
}
###
POST http://localhost:3003/api/login
Content-Type:application/json

{
  "name": "joao2",
  "email": "joao@te2fst.com"
}
###
POST http://localhost:3003/api/login
Content-Type:application/json

{
  "name": "admin",
  "email": "admin@admin.com"
}

###
PATCH http://localhost:3003/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwptOwofDmkcrw4RLacKIMVx1MDAwMMK6wrJcdTAwMGbDvSkreMKPVjvCr2_DuMOCXsO5N8KDI8O2wp5cdTAwMDIkcsOwecKIXHUwMDEyXHUwMDAweMOxw6vDnVx1MDAwZTTCo8KEScKZN1x1MDAwZsO4w65JUcOrOSRcdTAwMWNZwq5cdTAwMDNcdTAwMGZwwofDiMK8w7ttMcK3wrTCvsKYwptvI8KwVlx1MDAxNlLCqcO6w4fDucKfw63DtmhWwqomXHUwMDAyXHUwMDE2wqPCocOjwqHDlFLDrsOZwq9vXHUwMDFjwoXDjcOBYVx1MDAwM1Ynw4JcdFx1MDAxY8K4wrohXHUwMDE2w7TCmcK7w7pXWcO6ecK4wqLCkMKtXHUwMDBmXHUwMDAywqnDvsK9blfCj8OITcOnw4nCvsKvw6XCkFx0w7Z4M8KGwpjCuMKPwrHCm8OKMsK5w7txw5HDvVx1MDAwNMKBUcKMwr9Ow7VcZk0uwo7CtlTDlzZcdTAwMWFcdTAwMDR8fsO8L2DDj25sw4LCoMK7QlDDhVxyw4PDv8KTwpHDh8KZwpfDjVx1MDAxNF1cdTAwMDPDiVx1MDAxNcKzw5PCksOCfFxcw5TCvcO4wpw0NsKVwro_wqs-JsOLTFnCp3jCsy0kwoA1PcOFVlFkw4TDpX58P8K0J8OiwrBDw7QwIiwiaWF0IjoxNjE4MzYxNDg4LCJleHAiOjE2MTgzNjE3ODh9.Hi-2lRxDBxuM_-LB41yHMvG4ErjOi1X6rXW6_rwGtB0

{
   "email": "hghh@fgagalga.com"
}

###
DELETE http://localhost:3003/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwptOwofDmkcrw4RLacKIMVx1MDAwMMK6wrJcdTAwMGbDvSkreMKPVjvCr2_DuMOCXsO5N8KDI8O2wp5cdTAwMDIkcsOwecKIXHUwMDEyXHUwMDAweMOxw6vDnVx1MDAwZTTCo8KEScKZN1x1MDAwZsO4w65JUcOrOSRcdTAwMWNZwq5cdTAwMDNcdTAwMGZwwofDiMK8w7ttMcK3wrTCvsKYwptvI8KwVlx1MDAxNlLCqcO6w4fDucKfw63DtmhWwqomXHUwMDAyXHUwMDE2wqPCocOjwqHDlFLDrsOZwq9vXHUwMDFjwoXDjcOBYVx1MDAwM1Ynw4JcdFx1MDAxY8K4wrohXHUwMDE2w7TCmcK7w7pXWcO6ecK4wqLCkMKtXHUwMDBmXHUwMDAywqnDvsK9blfCj8OITcOnw4nCvsKvw6XCkFx0w7Z4M8KGwpjCuMKPwrHCm8OKMsK5w7txw5HDvVx1MDAwNMKBUcKMwr9Ow7VcZk0uwo7CtlTDlzZcdTAwMWFcdTAwMDR8fsO8L2DDj25sw4LCoMK7QlDDhVxyw4PDv8KTwpHDh8KZwpfDjVx1MDAxNF1cdTAwMDPDiVx1MDAxNcKzw5PCksOCfFxcw5TCvcO4wpw0NsKVwro_wqs-JsOLTFnCp3jCsy0kwoA1PcOFVlFkw4TDpX58P8K0J8OiwrBDw7QwIiwiaWF0IjoxNjE4MzYxNDg4LCJleHAiOjE2MTgzNjE3ODh9.Hi-2lRxDBxuM_-LB41yHMvG4ErjOi1X6rXW6_rwGtB0
###
POST http://localhost:3003/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDA3XHUwMDA0XHUwMDFlPcK-R8K9XHUwMDAwJcKeVVx1MDAxM8KaKMKERcO2wofClsK2w6_Cp1wiw5whw4JcdTAwMDdcdTAwMTPDumxuX8OOwrLDqlx1MDAwNX_DpFPDkSEtOMK6w4NewoXClSApXHQvXHUwMDBiw6_CusKnwoA2XHRqwrPCgcOyd8Otw5nDm1x1MDAxZMKrwrNcdTAwMTDDpMOnUWooK8OWW0tAQ8K0WVx1MDAxY8OXwqXDjkXDt8K2woLDiFLDhMK5Vzh1MsO_w47DnMKewpcpcMOZXFxoTUdcdTAwMDF1w4LDm8KDQ3FcdTAwMDLDlsOKwqfCg8KnwpZvY0XCh1x1MDAwMi4xw5FcdTAwMWU2wrdPwqDDrcKgwoTDjcO_XHUwMDE4w5LDn1x1MDAwNMOrf0REw7fCvy1ge1x1MDAxZGwzXHUwMDFiw5jCnEHCmF_Dl25cXMKPwq3DqMKtwrzCnHDCg2DDsG7CsmbDj8K-wqFYXHUwMDA0M8KBQMK0wq57O8KZQsKdw485wrhmXHUwMDA0XHUwMDAxfsKMwpXCg1x1MDAxOC5cdTAwMTfCg8OeUMOeT1x1MDAxM1xywp3DsMKgw5HClcOowptcZsOFw7_Cijo0wpHCszrDmlbCvlx1MDAxZcOiZmlrXHUwMDE3TEtcdTAwMDfCs8OHwrDDoktBwqTDssKEXHUwMDAzZSIsImlhdCI6MTYxODM2MzMzNCwiZXhwIjoxNjE4MzY2MzM0fQ.ZV9e6PkQlc5EUsDnXi47qMNlomyGobLf0Eaap5XeAgo
Content-Type: application/json

{
  "productId": "b890d511-46f1-4aca-bf6b-b324fbfadecc"
}
###
DELETE http://localhost:3003/api/users/favorites/b890d511-46f1-4aca-bf6b-b324fbfadecc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDA3XHUwMDA0XHUwMDFlPcK-R8K9XHUwMDAwJcKeVVx1MDAxM8KaKMKERcO2wofClsK2w6_Cp1wiw5whw4JcdTAwMDdcdTAwMTPDumxuX8OOwrLDqlx1MDAwNX_DpFPDkSEtOMK6w4NewoXClSApXHQvXHUwMDBiw6_CusKnwoA2XHRqwrPCgcOyd8Otw5nDm1x1MDAxZMKrwrNcdTAwMTDDpMOnUWooK8OWW0tAQ8K0WVx1MDAxY8OXwqXDjkXDt8K2woLDiFLDhMK5Vzh1MsO_w47DnMKewpcpcMOZXFxoTUdcdTAwMDF1w4LDm8KDQ3FcdTAwMDLDlsOKwqfCg8KnwpZvY0XCh1x1MDAwMi4xw5FcdTAwMWU2wrdPwqDDrcKgwoTDjcO_XHUwMDE4w5LDn1x1MDAwNMOrf0REw7fCvy1ge1x1MDAxZGwzXHUwMDFiw5jCnEHCmF_Dl25cXMKPwq3DqMKtwrzCnHDCg2DDsG7CsmbDj8K-wqFYXHUwMDA0M8KBQMK0wq57O8KZQsKdw485wrhmXHUwMDA0XHUwMDAxfsKMwpXCg1x1MDAxOC5cdTAwMTfCg8OeUMOeT1x1MDAxM1xywp3DsMKgw5HClcOowptcZsOFw7_Cijo0wpHCszrDmlbCvlx1MDAxZcOiZmlrXHUwMDE3TEtcdTAwMDfCs8OHwrDDoktBwqTDssKEXHUwMDAzZSIsImlhdCI6MTYxODM2MzMzNCwiZXhwIjoxNjE4MzY2MzM0fQ.ZV9e6PkQlc5EUsDnXi47qMNlomyGobLf0Eaap5XeAgo
Content-Type: application/json
###
GET http://localhost:3003/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDA3XHUwMDA0XHUwMDFlPcK-R8K9XHUwMDAwJcKeVVx1MDAxM8KaKMKERcO2wofClsK2w6_Cp1wiw5whw4JcdTAwMDdcdTAwMTPDumxuX8OOwrLDqlx1MDAwNX_DpFPDkSEtOMK6w4NewoXClSApXHQvXHUwMDBiw6_CusKnwoA2XHRqwrPCgcOyd8Otw5nDm1x1MDAxZMKrwrNcdTAwMTDDpMOnUWooK8OWW0tAQ8K0WVx1MDAxY8OXwqXDjkXDt8K2woLDiFLDhMK5Vzh1MsO_w47DnMKewpcpcMOZXFxoTUdcdTAwMDF1w4LDm8KDQ3FcdTAwMDLDlsOKwqfCg8KnwpZvY0XCh1x1MDAwMi4xw5FcdTAwMWU2wrdPwqDDrcKgwoTDjcO_XHUwMDE4w5LDn1x1MDAwNMOrf0REw7fCvy1ge1x1MDAxZGwzXHUwMDFiw5jCnEHCmF_Dl25cXMKPwq3DqMKtwrzCnHDCg2DDsG7CsmbDj8K-wqFYXHUwMDA0M8KBQMK0wq57O8KZQsKdw485wrhmXHUwMDA0XHUwMDAxfsKMwpXCg1x1MDAxOC5cdTAwMTfCg8OeUMOeT1x1MDAxM1xywp3DsMKgw5HClcOowptcZsOFw7_Cijo0wpHCszrDmlbCvlx1MDAxZcOiZmlrXHUwMDE3TEtcdTAwMDfCs8OHwrDDoktBwqTDssKEXHUwMDAzZSIsImlhdCI6MTYxODM2MzMzNCwiZXhwIjoxNjE4MzY2MzM0fQ.ZV9e6PkQlc5EUsDnXi47qMNlomyGobLf0Eaap5XeAgo
Content-Type: application/json

###
DELETE http://localhost:3003/api/user/baccb8b8-ccf5-44fd-b347-e0566421a10c
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXHUwMDA3XHUwMDA0XHUwMDFlPcK-R8K9XHUwMDAwJcKeVVx1MDAxM8KaKMKERcO2wofClsK2w6_Cp1wiw5whw4JcdTAwMDdcdTAwMTPDumxuX8OOwrLDqlx1MDAwNX_DpFPDkSEtOMK6w4NewoXClSApXHQvXHUwMDBiw6_CusKnwoA2XHRqwrPCgcOyd8Otw5nDm1x1MDAxZMKrwrNcdTAwMTDDpMOnUWooK8OWW0tAQ8K0WVx1MDAxY8OXwqXDjkXDt8K2woLDiFLDhMK5Vzh1MsO_w47DnMKewpcpcMOZXFxoTUdcdTAwMDF1w4LDm8KDQ3FcdTAwMDLDlsOKwqfCg8KnwpZvY0XCh1x1MDAwMi4xw5FcdTAwMWU2wrdPwqDDrcKgwoTDjcO_XHUwMDE4w5LDn1x1MDAwNMOrf0REw7fCvy1ge1x1MDAxZGwzXHUwMDFiw5jCnEHCmF_Dl25cXMKPwq3DqMKtwrzCnHDCg2DDsG7CsmbDj8K-wqFYXHUwMDA0M8KBQMK0wq57O8KZQsKdw485wrhmXHUwMDA0XHUwMDAxfsKMwpXCg1x1MDAxOC5cdTAwMTfCg8OeUMOeT1x1MDAxM1xywp3DsMKgw5HClcOowptcZsOFw7_Cijo0wpHCszrDmlbCvlx1MDAxZcOiZmlrXHUwMDE3TEtcdTAwMDfCs8OHwrDDoktBwqTDssKEXHUwMDAzZSIsImlhdCI6MTYxODM2MzMzNCwiZXhwIjoxNjE4MzY2MzM0fQ.ZV9e6PkQlc5EUsDnXi47qMNlomyGobLf0Eaap5XeAgo
###
GET http://localhost:3003/api/user?page=2
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwpjCk2JHXGbDvsOvRMO2w7RcdTAwMDc7MGXCr8ODL1x1MDAxY8KhbEFcdTAwMDXCjMKOI1x1MDAxYcKfKlx1MDAwZsOoJXbCi8KDw6h0wqJdb8K8w79cdTAwMWIwccKpLsODVMOKXHUwMDFkXHUwMDBmwoDDhsOOw6VcYsKNwqTDgFwiwoDChUhcdTAwMDJcdTAwMTBpcMKONcOscDvDvsOqPMKDdMOXNMO2w7lNXHUwMDFiwpNLwoHDs114w4jDsS1Uw4rCtU84X8OAZsKfwpVeVMKOesOhXHUwMDAyXHUwMDA1wrrDhnfDqSjDrUTCnMOGecKwXHUwMDAww5JDw4XDiMOFw5DCpcOka1x1MDAxNsKbXHUwMDEzWlx1MDAxOWxcdTAwMDbCgcKhLcOIw6JoXHUwMDA3f0piw5glwoXDtThxw63DusOfwqHDqFx1MDAwNVx1MDAxM1fCsVx1MDAxOMKraGInwphjwqXDqsO1XHUwMDE5woAxw4fDuk88WUXCgsOWXHUwMDFlcMOef8OORVJrwo_DtmPCu2DCpmfDgcORXHUwMDE4XHUwMDFmwqBcdTAwMWTCucORw7rCp8OywqfDmVx1MDAwYlx1MDAwYsKYw59cdTAwMTfCgsKhwqwwwrJ3w5JuwplcdTAwMDHCpCRow4guwpJ1LVx1MDAwMlx1MDAwMcOww4RcdTAwMDZcdTAwMDHCimtcdTAwMDfDi8OTajjChcOQwql1wofCjVxiwpVcdTAwMWEiLCJpYXQiOjE2MTgzNjQwMjcsImV4cCI6MTYxODM2NzAyN30.aF5wmJ_ZWyWKX4HQGFc_FsaE8UGsrp6q9HGKUCdbzac

###
PATCH http://localhost:3003/api/user/d0009652-2633-4562-998a-cca5c1143ef4
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwpjCk2JHXGbDvsOvRMO2w7RcdTAwMDc7MGXCr8ODL1x1MDAxY8KhbEFcdTAwMDXCjMKOI1x1MDAxYcKfKlx1MDAwZsOoJXbCi8KDw6h0wqJdb8K8w79cdTAwMWIwccKpLsODVMOKXHUwMDFkXHUwMDBmwoDDhsOOw6VcYsKNwqTDgFwiwoDChUhcdTAwMDJcdTAwMTBpcMKONcOscDvDvsOqPMKDdMOXNMO2w7lNXHUwMDFiwpNLwoHDs114w4jDsS1Uw4rCtU84X8OAZsKfwpVeVMKOesOhXHUwMDAyXHUwMDA1wrrDhnfDqSjDrUTCnMOGecKwXHUwMDAww5JDw4XDiMOFw5DCpcOka1x1MDAxNsKbXHUwMDEzWlx1MDAxOWxcdTAwMDbCgcKhLcOIw6JoXHUwMDA3f0piw5glwoXDtThxw63DusOfwqHDqFx1MDAwNVx1MDAxM1fCsVx1MDAxOMKraGInwphjwqXDqsO1XHUwMDE5woAxw4fDuk88WUXCgsOWXHUwMDFlcMOef8OORVJrwo_DtmPCu2DCpmfDgcORXHUwMDE4XHUwMDFmwqBcdTAwMWTCucORw7rCp8OywqfDmVx1MDAwYlx1MDAwYsKYw59cdTAwMTfCgsKhwqwwwrJ3w5JuwplcdTAwMDHCpCRow4guwpJ1LVx1MDAwMlx1MDAwMcOww4RcdTAwMDZcdTAwMDHCimtcdTAwMDfDi8OTajjChcOQwql1wofCjVxiwpVcdTAwMWEiLCJpYXQiOjE2MTgzNjQwMjcsImV4cCI6MTYxODM2NzAyN30.aF5wmJ_ZWyWKX4HQGFc_FsaE8UGsrp6q9HGKUCdbzac

{
  "email": "newwwwwww@fgagalga.com"
}