POST http://localhost:3001/api/register
Content-Type:application/json

{
  "name": "joao2",
  "email": "joao@te2fst.com"
}
###
POST http://localhost:3001/api/login
Content-Type:application/json

{
  "name": "joao2",
  "email": "joao@te2fst.com"
}

###
PATCH http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoifcKywo7DrcKSwrPClMOheGNwwqjDhsKow6Ncbi7DpXU1wpvCqHNMw5Rdw5zClsKLRy7Dk3NcdTAwMDLDoVx1MDAxYcKbwoFiwplOw4ZcdTAwMTTCjMKuwqPDgXvCrsKmbFPCu1x1MDAxNVx1MDAwZcOBwoBhw5XDm8KEeFx1MDAxNcKdRCjDvcKewr3DkVx1MDAwMsOvw57DrCY6XsKjfVx1MDAxZFx1MDAxN8KpwrpVw5rCiDTDjcKrXHUwMDFicsKHNlx1MDAxOVx1MDAxYybDqzJuw6XCn8OQOWFkWFxmeDQ3TypawqZUw5fColx1MDAwNjVdXGLCmXfCg1x1MDAxZcK0w43DsFx1MDAxY8OAIcO5XHUwMDFmTcOCXGbCqsOzw63CmcKkwo7Cp1x1MDAwMsOaw5jDg8KNwr4rw6LCkkV-wrh0wrRDw5DCuVx1MDAxNVx1MDAxZMOtwqHCh2PCk8KoXGZubU_Dj8Kcw6XDnG14wq9kw6J5w7nChlDDqMOlw6HCg8OWw73DqFx1MDAwNzh-wqXCvMKQYj_Co07CjcKZTsKfwplcdTAwMWZrTFx1MDAxZMORYnDCkCnDocOYS23DucOAwpPCtcO4RcOWUcK6N1x1MDAwYlx1MDAwMFDDmGvDvynDryMkw45aXHTCplfDm1xcw7HDtWvCisOiw77DlMO6SSIsImlhdCI6MTYxODE3NTQ1OSwiZXhwIjoxNjE4MTc1NzU5fQ.lFbAnvb5E38upLsn98k7YnMKaAYbjXx0dklLyPvIwGs

{
   "email": "aaaaa@fgagalga.com"
}

###
DELETE http://localhost:3001/api/user
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoifcKywo7DrcKSwrPClMOheGNwwqjDhsKow6Ncbi7DpXU1wpvCqHNMw5Rdw5zClsKLRy7Dk3NcdTAwMDLDoVx1MDAxYcKbwoFiwplOw4ZcdTAwMTTCjMKuwqPDgXvCrsKmbFPCu1x1MDAxNVx1MDAwZcOBwoBhw5XDm8KEeFx1MDAxNcKdRCjDvcKewr3DkVx1MDAwMsOvw57DrCY6XsKjfVx1MDAxZFx1MDAxN8KpwrpVw5rCiDTDjcKrXHUwMDFicsKHNlx1MDAxOVx1MDAxYybDqzJuw6XCn8OQOWFkWFxmeDQ3TypawqZUw5fColx1MDAwNjVdXGLCmXfCg1x1MDAxZcK0w43DsFx1MDAxY8OAIcO5XHUwMDFmTcOCXGbCqsOzw63CmcKkwo7Cp1x1MDAwMsOaw5jDg8KNwr4rw6LCkkV-wrh0wrRDw5DCuVx1MDAxNVx1MDAxZMOtwqHCh2PCk8KoXGZubU_Dj8Kcw6XDnG14wq9kw6J5w7nChlDDqMOlw6HCg8OWw73DqFx1MDAwNzh-wqXCvMKQYj_Co07CjcKZTsKfwplcdTAwMWZrTFx1MDAxZMORYnDCkCnDocOYS23DucOAwpPCtcO4RcOWUcK6N1x1MDAwYlx1MDAwMFDDmGvDvynDryMkw45aXHTCplfDm1xcw7HDtWvCisOiw77DlMO6SSIsImlhdCI6MTYxODE3NTQ1OSwiZXhwIjoxNjE4MTc1NzU5fQ.lFbAnvb5E38upLsn98k7YnMKaAYbjXx0dklLyPvIwGs
###
POST http://localhost:3001/api/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoifcKywo7DrcKSwrPClMOheGNwwqjDhsKow6Ncbi7DpXU1wpvCqHNMw5Rdw5zClsKLRy7Dk3NcdTAwMDLDoVx1MDAxYcKbwoFiwplOw4ZcdTAwMTTCjMKuwqPDgXvCrsKmbFPCu1x1MDAxNVx1MDAwZcOBwoBhw5XDm8KEeFx1MDAxNcKdRCjDvcKewr3DkVx1MDAwMsOvw57DrCY6XsKjfVx1MDAxZFx1MDAxN8KpwrpVw5rCiDTDjcKrXHUwMDFicsKHNlx1MDAxOVx1MDAxYybDqzJuw6XCn8OQOWFkWFxmeDQ3TypawqZUw5fColx1MDAwNjVdXGLCmXfCg1x1MDAxZcK0w43DsFx1MDAxY8OAIcO5XHUwMDFmTcOCXGbCqsOzw63CmcKkwo7Cp1x1MDAwMsOaw5jDg8KNwr4rw6LCkkV-wrh0wrRDw5DCuVx1MDAxNVx1MDAxZMOtwqHCh2PCk8KoXGZubU_Dj8Kcw6XDnG14wq9kw6J5w7nChlDDqMOlw6HCg8OWw73DqFx1MDAwNzh-wqXCvMKQYj_Co07CjcKZTsKfwplcdTAwMWZrTFx1MDAxZMORYnDCkCnDocOYS23DucOAwpPCtcO4RcOWUcK6N1x1MDAwYlx1MDAwMFDDmGvDvynDryMkw45aXHTCplfDm1xcw7HDtWvCisOiw77DlMO6SSIsImlhdCI6MTYxODE3NTQ1OSwiZXhwIjoxNjE4MTc1NzU5fQ.lFbAnvb5E38upLsn98k7YnMKaAYbjXx0dklLyPvIwGs
Content-Type: application/json

{
  "product_id": "123"
}