POST http://localhost:3002/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNEPComHDjEPDvMOgSTbChsOxRzbDm8OUXHUwMDFlXHUwMDE3XHTDqX1Nw5LDl2Jlw5DChSsjJMKmKcKtc8KUXHUwMDFmecODXHUwMDFmSl1ZwqnDvH1xw4vDjsOaZVTCgHTCrMO9wr9cdTAwMWHDsMKCw6p8XHUwMDE2XHUwMDA1wrVgw7fChFx1MDAwN8KqO8KHfC7CnEpxw64uw4RcdTAwMTPDu8OMXHUwMDFmK8Ojw5vDs8Oww5NcdTAwMGJcdTAwMWM6w4hMbDBcdTAwMTTCssO6wqpBXHRIXkk-wr8wwrFswpdzTW_DtTPCp1Rnw5fDu8OLw4XClmnDn8OFw7FJw4Ehwo_DjFwiw5XDkcOvXHUwMDBldirCi1x1MDAxZMOfwozDtVXCgS87wrhcdTAwMThcdTAwMTnCnFx1MDAxOVx0w59fJMKkY1x1MDAwMsOSwpVIwrVIY0TCoMK-QSlcdTAwMGLCuWTCpjJcdTAwMDNcIsOMw6NgwoTDu2bDosOPWGonXHUwMDE3LijDmcOfW8OWw7bDjMOBw6tBw7l1w73DnH7Ch8Oyw6DDrsK0XHUwMDA0c0PDn35DTsKGw7jCpsK4UnpQwpA3w4DCv8OAwozDjzNwXHUwMDAxw7vDnVx1MDAwMmVww4nDj8Ovw4LDj8KbXGLDg8O0w6Ngw4BiXHUwMDFhIiwiaWF0IjoxNjE4MzY0NTgxLCJleHAiOjE2MTgzNjc1ODF9.thRefh-9yAEi_pLUHxoFUYN-41cthxFTTlpAXABwdMI

{
  "price": 132,
  "image": "http://www.google.coim",
  "brand": "test",
  "title": "test",
  "reviewScore": 1
}

###
GET http://localhost:3002/api/product/b890d511-46f1-4aca-bf6b-b324fbfadecc
Content-Type: application/json
###
GET http://localhost:3002/api/product
Content-Type: application/json