POST http://localhost:3000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiwonCo0rCkiZcdTAwMWLDiVxyw7l9IFrCvsKUw40zw7ZcdTAwMTZUwpXCgFxiwqBuw6lhw7E3XHUwMDEww71cdTAwMDHCrFx1MDAwN3rDl1PDm1x1MDAwMcK-w5vCjMOOSsO1woDCt8KNw4HDn8ORck_DlMKke8KVwo7DqlkjwqEowpdMbVx1MDAwNsK8O8K0w53Coih_w5xcdTAwMDXCkcOcwpnCkSTDu3XDs8OUwrpEw6HCoFx1MDAwN0M-wqRcdTAwMGUxasOOwrJpwrxbRCBGIMKvwojDmMKjw5XCgsOnw5tcdTAwMDbChMO3XHUwMDE5MMONXHUwMDBlWMKmXHUwMDA0XHUwMDA0XHUwMDE1UHM6UkwvNTYwwqFcdTAwMGVcIkHDgMOFPW5PUltsXHUwMDEwwrDDtiVcdTAwMTI4wq3Dilx1MDAxZWfDlkBRXHQ6XHUwMDE1LcOJa8Kqwp_CkHbDiyvCpmTDkMKZVcK-QCHDky9tXHUwMDFhaiTDscK2w6QzdcKsXHUwMDAxw7lnT8K3OldqbCBzXHUwMDFjXHUwMDA0XsOBXHUwMDExwqdcdTAwMWTDnVx1MDAxMCtcdTAwMTXCvsKUJy3Cg2lcdTAwMTfDgy5pw4VcZsKKQMK4wpDCgcK5wrnDkHTCnVUrw61Uw6_CvsKmw4Bqw6LDp8OUw53CjMKvw7dCw4bDhcK8c1ciLCJpYXQiOjE2MTg0Mzc1MzUsImV4cCI6MTYxODQ0MDUzNX0.Z_fnZXichrldt5eqXicg3YRU2QkzXh9j3Y9M0ejS7Y0

{
  "price": 132,
  "image": "http://www.google.coim",
  "brand": "test",
  "title": "test",
  "reviewScore": 1
}

###
GET http://localhost:3002/api/product/b890d511-46f1-4aca-bf6b-b324fbfadecc
Content-Type: application/json
###
GET http://localhost:3002/api/product
Content-Type: application/json